apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ABCCapital
  description: "Es un indice"
  annotations: 
    elasticsearch/index-name: abccapital-site247-24-10-2023
spec:
  lifecycle: experimental
  owner: prophecy
  type: service
